# Reshaping Arrays

Using `reshape()`, `-1` to infer dimensions, flattening, and `order` parameter.

In [ ]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6])
# Reshape to 2 rows and 3 columns
matrix = arr.reshape(2, 3)
print(matrix)


In [ ]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8])
# Reshape to 2 blocks, each having 2 rows and 2 columns
tensor = arr.reshape(2, 2, 2)
print(tensor)


In [ ]:
matrix = np.array([[1, 2], [3, 4]])
flat = matrix.reshape(-1)
print(flat)


In [2]:
import numpy as np
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])
# Let NumPy infer the columns
new_arr = arr.reshape(3, -1)
print(new_arr)


[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [ ]:
arr = np.array([1, 2, 3, 4, 5, 6])
# C-Order (Default)
print(arr.reshape((2, 3), order='C'))

# F-Order
print(arr.reshape((2, 3), order='F'))
