In [2]:
#5 x 5 array filled with zeros

import numpy as np

null_matrix = np.zeros((5, 5))
print(null_matrix)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


In [3]:
identity_matrix = np.identity(4)
print(identity_matrix)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [14]:
random_array = np.random.randint(1, 101, size=20)
print(random_array)

print(np.max(random_array))
print(np.min(random_array))
print(np.mean(random_array))



[ 80  42  61  51   4  26  58  40  76  84  84  14  80  30  83   7   7  19
 100  82]
100
4
51.4


In [16]:
one_to_five = np.arange(1, 6)
print(one_to_five)
print(one_to_five ** 2)

[1 2 3 4 5]
[ 1  4  9 16 25]


In [18]:
array = np.array([[1, 2, 3],
                  [4, 5, 6]])
print(array[1, 1:2])

[5]
