The Syntax and "The Tuple Trap"
The most common mistake beginners make with concatenate happens on day one, and it throws a TypeError.

Incorrect: np.concatenate(array1, array2)

Correct: np.concatenate((array1, array2))

Why? The first argument of concatenate must be a sequence (a tuple or a list) of the arrays you want to join. If you pass them as separate arguments, NumPy thinks array2 is the axis parameter.

Example: Joining 1D Arrays

In [ ]:
import numpy as np

a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

# Notice the extra parentheses! We are passing a tuple (a, b)
joined = np.concatenate((a, b))

print(joined)
# Output: [1 2 3 4 5 6]

The axis Parameter (The Core of Concatenation)
When you move beyond 1D arrays into matrices (2D) or tensors (3D+), you have to tell NumPy how you want them stitched together. You do this using the axis parameter.

axis=0 (Default): Joins along the first dimension (rows). Think of this as stacking them vertically, one on top of the other.

axis=1: Joins along the second dimension (columns). Think of this as stacking them horizontally, side-by-side.

axis=None: A special case. If you set axis to None, NumPy will flatten() all the arrays into 1D first, and then concatenate them into one long 1D array.

In [ ]:
matrix1 = np.array([[1, 2], 
                    [3, 4]])

matrix2 = np.array([[5, 6], 
                    [7, 8]])

# Vertical Stack (axis=0)
vert = np.concatenate((matrix1, matrix2), axis=0)
print("Vertical (axis=0):\n", vert)
# Output:
# [[1 2]
#  [3 4]
#  [5 6]
#  [7 8]]

# Horizontal Stack (axis=1)
horiz = np.concatenate((matrix1, matrix2), axis=1)
print("\nHorizontal (axis=1):\n", horiz)
# Output:
# [[1 2 5 6]
#  [3 4 7 8]]