In [1]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6])
# Reshape to 2 rows and 3 columns
matrix = arr.reshape(2, 3) 
print(matrix)



[[1 2 3]
 [4 5 6]]


In [3]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8])
# Reshape to 2 blocks, each having 2 rows and 2 columns
tensor = arr.reshape(2, 2, 2)
print(tensor)


[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [ ]:
matrix = np.array([[1, 2], [3, 4]])
flat = matrix.reshape(-1)
print(flat)


[1 2 3 4]


In [6]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])
# Tell NumPy: "Give me 3 rows, you calculate the columns"
new_arr = arr.reshape(3, -1) 
# NumPy automatically calculates 4 columns (12 / 3 = 4)
print(new_arr)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [7]:
arr = np.array([1, 2, 3, 4, 5, 6])

# C-Order (Default)
print(arr.reshape((2, 3), order='C'))
# [[1, 2, 3],
#  [4, 5, 6]]

# F-Order
print(arr.reshape((2, 3), order='F'))
# [[1, 3, 5],
#  [2, 4, 6]]


[[1 2 3]
 [4 5 6]]
[[1 3 5]
 [2 4 6]]


In [8]:
import numpy as np

# Create a 2D array
original_arr = np.array([[1, 2], [3, 4]])

# Flatten it
flat_arr = original_arr.flatten()

# Modify the flattened array
flat_arr[0] = 99

print("Original Array:\n", original_arr)
# Output: 
# [[1 2]
#  [3 4]]  <-- Remains unchanged

print("Flattened Array:\n", flat_arr)
# Output: 
# [99  2  3  4]

Original Array:
 [[1 2]
 [3 4]]
Flattened Array:
 [99  2  3  4]


In [ ]:
import numpy as np

# Create a 2D array
original_arr = np.array([[1, 2], [3, 4]])

# Ravel it
raveled_arr = original_arr.ravel()

# Modify the raveled array
raveled_arr[0] = 99

print("Original Array:\n", original_arr)
# Output: 
# [[99  2]
#  [ 3  4]]  <-- Changed! The original was modified.

print("Raveled Array:\n", raveled_arr)
# Output: 
# [99  2  3  4]

The order Parameter
Both functions accept an order keyword argument that dictates how the multi-dimensional array is read to form the 1D array.

order='C' (Default): C-style / Row-major. Reads elements row by row.

order='F': Fortran-style / Column-major. Reads elements column by column.

order='A': Reads elements in the order they are stored in memory (Fortran-like if the array is Fortran-contiguous, otherwise C-like).

order='K': Reads elements strictly in the order they occur in memory.

Example of 'C' vs 'F' Order: