The Big Trap: Function vs. Method

You must pay close attention to whether you are using the NumPy module function (np.resize()) or the array object method (arr.resize()).

np.resize(arr, shape) (The Function): Returns a new copy. If you make the array larger, it fills the missing spaces by repeating the original data.

arr.resize(shape) (The Method): Modifies the array in-place. If you make the array larger, it fills the missing spaces with zeros.

import numpy as np

arr = np.array([1, 2, 3, 4])

# Shrinking (cuts off the extra elements)
shrunk = np.resize(arr, (2,))
print("Shrunk:\n", shrunk)
# Output: [1 2]

# Expanding (repeats the elements cyclically)
expanded = np.resize(arr, (2, 4))
print("\nExpanded:\n", expanded)
# Output:
# [[1 2 3 4]
#  [1 2 3 4]]  <-- Notice how it repeats the data to fill the void

In [ ]:
import numpy as np

arr = np.array([1, 2, 3, 4])

# Modifying in-place to be a 2x3 matrix (needs 6 elements)
arr.resize((2, 3))

print(arr)
# Output:
# [[1 2 3]
#  [4 0 0]]  <-- Notice the zeros padding the end!