In [1]:
import numpy as np

# Create a 2x3 matrix
matrix = np.array([[1, 2, 3], 
                   [4, 5, 6]])

# Transpose it using .T
transposed = matrix.T

print("Original Shape:", matrix.shape)  # Output: (2, 3)
print("Transposed Shape:", transposed.shape) # Output: (3, 2)

print("\nTransposed Matrix:\n", transposed)
# Output:
# [[1 4]
#  [2 5]
#  [3 6]]

Original Shape: (2, 3)
Transposed Shape: (3, 2)

Transposed Matrix:
 [[1 4]
 [2 5]
 [3 6]]


In [ ]:
arr_1d = np.array([1, 2, 3])
print(arr_1d.shape)    # Output: (3,)
print(arr_1d.T.shape)  # Output: (3,) -- Nothing changed!

# Convert to a 2D row vector (shape: 1x3)
row_vector = arr_1d[np.newaxis, :] 

# Now you can transpose it to a column vector (shape: 3x1)
col_vector = row_vector.T 

print(col_vector)
# Output:
# [[1]
#  [2]
#  [3]]

Advanced: Transposing N-Dimensional Arrays (Tensors)
When you have arrays with 3 or more dimensions (like image data or deep learning tensors), .T will simply reverse all axes. For example, a shape of (2, 3, 4) becomes (4, 3, 2).

But what if you only want to swap specific axes? This is where np.transpose(arr, axes) shines. The axes parameter takes a tuple of integers representing the new order of the dimensions.

Example: Swapping specific axes in a 3D array
Imagine you have an array representing a batch of images with the shape (Batch, Height, Width, Channels). Sometimes, machine learning frameworks require the shape to be (Batch, Channels, Height, Width).

In [ ]:
# Shape: (2 batches, 10 height, 10 width, 3 color channels)
# The current axes indices are: (0, 1, 2, 3)
images = np.zeros((2, 10, 10, 3)) 

# We want to move the Channels (axis 3) to be right after the Batch (axis 0).
# The new axis order we want is: 0, 3, 1, 2
reshaped_images = np.transpose(images, axes=(0, 3, 1, 2))

print(reshaped_images.shape) 
# Output: (2, 3, 10, 10)